# Generated by cucumber-sinatra. (2014-10-03 11:42:02 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/rockpaperscissors.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = ROCKPAPERSCISSORS

class ROCKPAPERSCISSORSWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  ROCKPAPERSCISSORSWorld.new
end
